# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LeCuistotduWeb
email: gaetan.boyron@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Développeur Web - Conception et développement d'interfaces Web.
baseurl: "" # the subpath of your site, e.g. /blog
url:  "https://lecuistotduweb.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

github_url:  https://github.com/LeCuistotduWeb
linkedin_url:  https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_top_card%3B5i7yDluiT9y1sZa7X%2BYKOw%3D%3D

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: pretty

# collections
collections:
  works:
    output: true
    

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
